"""
Typst rendering engine for FEA reports — standalone .typ output.
Generates self-contained Typst files that compile directly with `typst compile`.
"""

from datetime import datetime

from .config import FORCE_COLUMNS, STRESS_COLUMNS, STRIP_WIDTH
from .math_utils import format_value
from .reporting import _format_loc


# =============================================================================
# Typst preamble — clean academic style
# =============================================================================
TYPST_PREAMBLE = """\
// FEA Results Summary Report
// Generated by FEA Contour Plotter
// Compile with: typst compile <filename>.typ

#set page(
  paper: "a4",
  margin: (x: 2cm, y: 2.5cm),
  numbering: "1",
)
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set table(
  inset: 6pt,
  stroke: 0.5pt + luma(180),
)
#show table.cell.where(y: 0): set text(weight: "bold")
#show heading.where(level: 1): set text(size: 16pt)
#show heading.where(level: 2): set text(size: 13pt)
#show heading.where(level: 3): set text(size: 11pt)
"""


def _tv(v):
    """Format a numeric value for Typst table cell."""
    return format_value(v) if isinstance(v, (int, float)) else str(v)


def _tloc(loc, elem_id=None):
    """Format location for Typst table cell."""
    x, y = loc
    if elem_id is not None:
        return f"Elem {elem_id} ({x:.2f}, {y:.2f})"
    return f"({x:.2f}, {y:.2f})"


def render_report_typst(title, stats, n_points, thickness, method):
    """
    Render a single-source report as Typst string.

    Parameters
    ----------
    title : str
    stats : dict — output of extract_statistics()
    n_points : int
    thickness : float
    method : str

    Returns
    -------
    str — complete Typst content
    """
    lines = [TYPST_PREAMBLE]

    # Title
    lines.append(f"= FEA Results Summary")
    lines.append(f"== {title}")
    lines.append("")
    lines.append(f"#text(size: 9pt)[")
    lines.append(f"  *Generated:* {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} \\")
    lines.append(f"  *Plate Thickness:* {thickness * 1000:.0f} mm \\")
    lines.append(f"  *Strip Width:* {STRIP_WIDTH:.1f} m \\")
    lines.append(f"  *Contour Method:* {method.replace('-', ' ').title()} \\")
    lines.append(f"  *Total Data Points:* {n_points:,}")
    lines.append(f"]")
    lines.append("")

    # Section Properties
    area = thickness * STRIP_WIDTH
    inertia = (STRIP_WIDTH * thickness ** 3) / 12
    lines.append("== Section Properties")
    lines.append("")
    lines.append("#table(")
    lines.append("  columns: (1fr, 1fr, auto),")
    lines.append("  table.header([Parameter], [Value], [Unit]),")
    lines.append(f'  [Area (A)], [{area:.6f}], [m\\u00b2],')
    lines.append(f'  [Inertia (I)], [{inertia:.6f}], [m\\u2074],')
    lines.append(")")
    lines.append("")

    # Force/Moment Summary
    force_cols = [c for c in FORCE_COLUMNS if c in stats]
    if force_cols:
        lines.append("== Force & Moment Summary")
        lines.append("")
        for col in force_cols:
            e = stats[col]
            lines.append(f"=== {col}")
            lines.append("")
            lines.append("#table(")
            lines.append("  columns: (auto, 1fr, auto),")
            lines.append("  table.header([Statistic], [Value], [Location]),")
            lines.append(f'  [*Maximum*], [{_tv(e["max"])}], [{_tloc(e["max_loc"], e.get("max_elem"))}],')
            lines.append(f'  [*Minimum*], [{_tv(e["min"])}], [{_tloc(e["min_loc"], e.get("min_elem"))}],')
            lines.append(f'  [Mean], [{_tv(e["mean"])}], [-],')
            lines.append(")")
            lines.append("")

    # Stress Summary
    stress_cols = [c for c in STRESS_COLUMNS if c in stats]
    if stress_cols:
        lines.append("== Stress Summary (kPa)")
        lines.append("")
        lines.append("_Sign Convention: Positive Moment -> Top Compression (-), Bottom Tension (+)_")
        lines.append("")
        for col in stress_cols:
            e = stats[col]
            f_max = _tv(e.get('max_F', '-'))
            m_max = _tv(e.get('max_M', '-'))
            f_min = _tv(e.get('min_F', '-'))
            m_min = _tv(e.get('min_M', '-'))
            lines.append(f"=== {col}")
            lines.append("")
            lines.append("#table(")
            lines.append("  columns: (auto, 1fr, auto, auto, auto),")
            lines.append("  table.header([Statistic], [Value], [Location], [F (kN/m)], [M (kN.m/m)]),")
            lines.append(f'  [*Maximum*], [{_tv(e["max"])}], [{_tloc(e["max_loc"], e.get("max_elem"))}], [{f_max}], [{m_max}],')
            lines.append(f'  [*Minimum*], [{_tv(e["min"])}], [{_tloc(e["min_loc"], e.get("min_elem"))}], [{f_min}], [{m_min}],')
            lines.append(f'  [Mean], [{_tv(e["mean"])}], [-], [-], [-],')
            lines.append(")")
            lines.append("")

    return '\n'.join(lines)


def render_master_typst(envelope, thickness, method):
    """
    Render master summary as Typst string.

    Parameters
    ----------
    envelope : dict — output of compute_master_envelope()
    thickness : float
    method : str

    Returns
    -------
    str — complete Typst content
    """
    lines = [TYPST_PREAMBLE]

    lines.append("= FEA Master Summary")
    lines.append("== All Load Cases & Combinations")
    lines.append("")
    lines.append("#text(size: 9pt)[")
    lines.append(f"  *Generated:* {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} \\")
    lines.append(f"  *Total Items Analyzed:* {envelope['total_sources']} "
                 f"({envelope['total_lc']} Load Cases + {envelope['total_combo']} Combinations) \\")
    lines.append(f"  *Plate Thickness:* {thickness * 1000:.0f} mm | "
                 f"*Strip Width:* {STRIP_WIDTH:.1f} m | "
                 f"*Method:* {method.replace('-', ' ').title()}")
    lines.append("]")
    lines.append("")
    lines.append("#line(length: 100%, stroke: 0.5pt + luma(180))")
    lines.append("")

    # 1. Global Stress Envelope — Top 20
    lines.append("== Global Stress Envelope")
    lines.append("")
    lines.append("=== Top 20 Absolute Maximum Stresses (All Sources)")
    lines.append("")
    lines.append("#table(")
    lines.append("  columns: (auto, auto, auto, 1fr, auto, auto, auto),")
    lines.append("  table.header([Rank], [Source], [Stress Col], [Value (kPa)], [Location], [F (kN/m)], [M (kN.m/m)]),")

    for i, e in enumerate(envelope['stress_entries'][:20], 1):
        f_str = _tv(e['F']) if 'F' in e else '-'
        m_str = _tv(e['M']) if 'M' in e else '-'
        loc_str = _tloc(e['loc'], e.get('elem'))
        lines.append(f'  [{i}], [{e["source"]}], [{e["col"]}], '
                     f'[{_tv(e["value"])}], [{loc_str}], [{f_str}], [{m_str}],')

    lines.append(")")
    lines.append("")
    lines.append("#line(length: 100%, stroke: 0.5pt + luma(180))")
    lines.append("")

    # 2. Detailed Extremes per Stress Type
    for col in STRESS_COLUMNS:
        col_entries = [e for e in envelope['stress_entries'] if e['col'] == col]
        if not col_entries:
            continue
        lines.append(f"=== {col} - Detailed Extremes")
        lines.append("")
        lines.append("#table(")
        lines.append("  columns: (auto, 1fr, auto, auto, auto, auto),")
        lines.append("  table.header([Type], [Value (kPa)], [Location], [Source], [F (kN/m)], [M (kN.m/m)]),")

        maxes = [e for e in col_entries if e['type'] == 'MAX']
        mins = [e for e in col_entries if e['type'] == 'MIN']
        if maxes:
            best = max(maxes, key=lambda x: x['value'])
            f_s = _tv(best.get('F', 0)) if 'F' in best else '-'
            m_s = _tv(best.get('M', 0)) if 'M' in best else '-'
            lines.append(f'  [*Global Max*], [{_tv(best["value"])}], '
                         f'[{_tloc(best["loc"], best.get("elem"))}], [{best["source"]}], [{f_s}], [{m_s}],')
        if mins:
            best = min(mins, key=lambda x: x['value'])
            f_s = _tv(best.get('F', 0)) if 'F' in best else '-'
            m_s = _tv(best.get('M', 0)) if 'M' in best else '-'
            lines.append(f'  [*Global Min*], [{_tv(best["value"])}], '
                         f'[{_tloc(best["loc"], best.get("elem"))}], [{best["source"]}], [{f_s}], [{m_s}],')

        lines.append(")")
        lines.append("")

    # 3. Global Force/Moment Envelope
    lines.append("#line(length: 100%, stroke: 0.5pt + luma(180))")
    lines.append("")
    lines.append("== Global Force & Moment Envelope")
    lines.append("")

    force_col_groups = {}
    for e in envelope['force_entries']:
        col = e['col']
        if col not in force_col_groups:
            force_col_groups[col] = []
        force_col_groups[col].append(e)

    for col in FORCE_COLUMNS:
        entries = force_col_groups.get(col, [])
        if not entries:
            continue
        entries.sort(key=lambda x: abs(x['value']), reverse=True)
        lines.append(f"=== {col}")
        lines.append("")
        lines.append("#table(")
        lines.append("  columns: (auto, auto, 1fr, auto),")
        lines.append("  table.header([Rank], [Source], [Value], [Location]),")
        for i, e in enumerate(entries[:5], 1):
            lines.append(f'  [{i}], [{e["source"]}], [{_tv(e["value"])}], '
                         f'[{_tloc(e["loc"], e.get("elem"))}],')
        lines.append(")")
        lines.append("")

    return '\n'.join(lines)
